### ISSUE TITLE
Safe mode strips valid data out of tags when they exceed known limits

### ISSUE THREAD

**Issue by gbMichelle** [MosesofEgypt/refinery#2]
I think we should either solve this by only applying these cleanups when clicking deprotect, or have a warning box pop up with the affected tag before this can be applied, as a confirmation. (Preferably have a list of all tags affected where this can be either approved or dissaproved by the user.)

**Comment by MosesofEgypt** [comment]
The data stripping occurs upon extraction, so it doesn't affect the map at all. Indices and sizes get changed, so it can't possibly be applied to the map upon map deprotection. It's also not possible to determine with certainty that a tag has these protections applied to them until its been extracted and you can look through the data. This is where the cleaning is invoked, and a few lines below is the cleaning function. The cleaning methods are all ad-hoc for each tag type.
https://github.com/MosesofEgypt/reclaimer/blob/master/meta/wrappers/halo1_map.py#L472

**Comment by gbMichelle** [comment]
Thanks. I have some ideas after looking at that. I'll show you what I've come up with when I get there.

**Comment by MosesofEgypt** [comment]
Closing this issue, as the question and solution rely on incorrect assumptions about how the tag cleaning works, and why it works that way.

**Comment by gbMichelle** [comment]
I was thinking of finding the highest used index by going through the units array and finding the highest referenced number in there. Also bumping up the animations limit to the Opensauce limit as everyone uses sets that break that nowadays.
